### ISSUE TITLE
Révisions classe Artefacts

### ISSUE THREAD

**Issue by emchateau** [technes/dataModel#3]
- [x] conserver n° de série
- [x] supprimer restrictions d’acccès
- [x] renommer catégorie en stade de processus de réalisation du film, étape, process, phase, etc. 
- [x] liste des étapes : préproduction, production et tournage, postproduction, diffusion, conservation
- [x] utiliser nomObjet au lieu de type d’appareil
- [x] passer typeAppareil dans Autre
- [x] désignation : Louis dit que s’accomode assez bien de valeurs normalisé mais paraît essentiel
- [x] définir une règle de gestion, et demander à Idée-clic : type objet, format, fabricant, modèle (définir une règle de gestion)
- [x] format : cf thesaurus
- [x] média : pré-cinéma, cinéma, vidéo, numérique
- [x] modèle supprimer
- [x] estPortable, rendre optionnel

réunion avec Louis

**Comment by IsabelleLHeureux** [comment]
- [x] Matière : à changer pour Matériaux
- [x] Descripteur technique : permet d'accéder à plusieurs parties du thésaurus et est un champ répétable OU texte libre
- [x] Archives : supprimer (table à part) et nommer autrement, lieu de conservation par exemple
- [x] artefact associé : supprimer et rendre possible la relation "artefact-artefact"
- [x] attachement : supprimer et établir une relation avec d'autres documents dont les reproductions
- [x] hyperliens : pareil
- [x] commentaire privé : nommer "note de travail"
- [x] parcours : supprimer

**Comment by IsabelleLHeureux** [comment]
@emchateau 
Vu avec @remybesson @pelletieroscope : 
La règle de gestion pour Désignation pourrait être : 
"Désignation de l'objet" : Type d’appareil, Fabricant, Marque de commerce, Modèle, Texte libre
(un champ complété automatiquement en fonction d'autres champs du formulaire et au quel du texte libre pourrait être ajouté à la fin)
